// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicHN0_OgcUXmwXbwIjW5nrVkzQ1qvowA',
    appId: '1:97970043333:web:bac39c55f34b9412ccf3ac',
    messagingSenderId: '97970043333',
    projectId: 'inventory-management-7026f',
    authDomain: 'inventory-management-7026f.firebaseapp.com',
    storageBucket: 'inventory-management-7026f.firebasestorage.app',
    measurementId: 'G-FMNSTLTN25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQ2jIpGF5PuYs1nUpeHKERpBxOvDLtRw',
    appId: '1:97970043333:android:9a7fd52227bf528cccf3ac',
    messagingSenderId: '97970043333',
    projectId: 'inventory-management-7026f',
    storageBucket: 'inventory-management-7026f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfNvxwFFW9hldP6r0khjnrgT2t2pZG3I',
    appId: '1:97970043333:ios:c0026e44cfa33921ccf3ac',
    messagingSenderId: '97970043333',
    projectId: 'inventory-management-7026f',
    storageBucket: 'inventory-management-7026f.firebasestorage.app',
    iosBundleId: 'com.example.icw12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYfNvxwFFW9hldP6r0khjnrgT2t2pZG3I',
    appId: '1:97970043333:ios:c0026e44cfa33921ccf3ac',
    messagingSenderId: '97970043333',
    projectId: 'inventory-management-7026f',
    storageBucket: 'inventory-management-7026f.firebasestorage.app',
    iosBundleId: 'com.example.icw12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicHN0_OgcUXmwXbwIjW5nrVkzQ1qvowA',
    appId: '1:97970043333:web:bae068b1776e3ceaccf3ac',
    messagingSenderId: '97970043333',
    projectId: 'inventory-management-7026f',
    authDomain: 'inventory-management-7026f.firebaseapp.com',
    storageBucket: 'inventory-management-7026f.firebasestorage.app',
    measurementId: 'G-T6M2PLVFNS',
  );
}
